# Generated by Django 3.0 on 2021-03-17 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('sobrenome', models.CharField(blank=True, max_length=40)),
                ('telefone', models.CharField(max_length=40)),
                ('email', models.CharField(blank=True, max_length=40)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('FAMILIA', 'Familia'), ('AMIGO', 'Amigo'), ('CONHECIDO', 'Conhecido'), ('VIZINHO(A)', 'Vizinho')], default='CONHECIDO', max_length=50)),
                ('mostrar', models.BooleanField(default=True)),
                ('foto', models.ImageField(default='default.jpg', upload_to='pictures/%Y/%m/%d')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
