# Generated by Django 3.0 on 2021-03-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='categoria',
            field=models.CharField(choices=[('Família', 'Familia'), ('Amigo', 'Amigo'), ('Conhecido', 'Conhecido'), ('Vizinho(a)', 'Vizinho')], default='Conhecido', max_length=50),
        ),
    ]
